__info__ = "This project uses llm-context. For more information, visit: https://github.com/cyberchitta/llm-context.py or https://pypi.org/project/llm-context/"

[templates]
context = "lc-context.j2"
context-mcp = "lc-context-mcp.j2"
files = "lc-files.j2"
highlights = "lc-highlights.j2"
prompt = "lc-prompt.j2"

[profiles.code]
prompt = "lc-prompt.md"
[profiles.code.gitignores]
full_files = [
    ".github/",
    ".devcontainer/",
    ".vscode/",
    "notebooks/",
    "test/",
    "openapi",
    "assets/",
    ".git",
    ".gitignore",
    ".llm-context/",
    "*.tmp",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "go.sum",
    "elm-stuff",
    "LICENSE",
    "CHANGELOG.md",
    "README.md",
    ".env",
    ".dockerignore",
    "Dockerfile",
    "docker-compose.yml",
    "*.log",
    "*.svg",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.ico",
    "*.woff",
    "*.woff2",
    "*.eot",
    "*.ttf",
    "*.map",
]
outline_files = [
    ".git",
    ".gitignore",
    ".llm-context/",
    "*.tmp",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "go.sum",
    "elm-stuff",
    "LICENSE",
    "CHANGELOG.md",
    "README.md",
    ".env",
    ".dockerignore",
    "Dockerfile",
    "docker-compose.yml",
    "*.log",
    "*.svg",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.ico",
    "*.woff",
    "*.woff2",
    "*.eot",
    "*.ttf",
    "*.map",
]

[profiles.code.only-include]
full_files = ["**/*"]
outline_files = ["**/*"]

[profiles.code.settings]
no_media = false
with_user_notes = false
with_prompt = false

[profiles.code-prompt]
base = "code"

[profiles.code-prompt.settings]
with_prompt = true

[profiles.code-file]
base = "code"

[profiles.code-file.settings]
context_file = "project-context.md.tmp"
