__info__: 'This project uses llm-context. For more information, visit: https://github.com/cyberchitta/llm-context.py
  or https://pypi.org/project/llm-context/'
templates:
  context: lc-context.j2
  context-mcp: lc-context-mcp.j2
  definitions: lc-definitions.j2
  files: lc-files.j2
  highlights: lc-highlights.j2
  prompt: lc-prompt.j2
